# Generated by Django 3.2.8 on 2023-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230329_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={},
        ),
        migrations.AlterField(
            model_name='fooddata',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fooddata',
            name='methane',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fooddata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterModelTable(
            name='fooditem',
            table=None,
        ),
    ]
