# Generated by Django 3.2.8 on 2023-03-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230330_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddata',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
