# Generated by Django 3.2.8 on 2023-04-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fooddata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddata',
            name='Quality',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
